apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  replicas: 3
  podTemplate:
    spec:
      securityContext:
        fsGroup: 10000    # to make the data directory writable for `mysqld` container.
        fsGroupChangePolicy: "OnRootMismatch"  # available since k8s 1.20
      containers:
      - name: mysqld
        image: quay.io/cybozu/mysql:8.0.26 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
