{{- if .Values.varnish.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-varnishw
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-varnishw
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-varnishw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-varnishw
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-varnishw
  namespace: {{ .Release.Namespace }}
{{- end }}
